print("Hello")
print("Welcome to my world")
print("This project is for to combine two git hubs")
print("I am adding the data as Hii I am Kesararanjitha")
print("I want to study")
print("I aim to become a software engineer")
print("And want to dance")
print("I have no luck at any time and any where")
